version: '3.7'
services:

  ####################################
  # Begin Fixtures
  ####################################
  neo4j:
    image: menome/thelink-neo4j-main:latest
    # build: fixtures/neo4j
    ports:
      - "7473:7473"   # web interface (SSL)
      - "7474:7474"   # web interface
      - "7687:7687"   # bolt
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*  
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_max__size=10G
      - NEO4J_dbms_memory_pagecache_size=2G   
      - NEO4J_ENCTRYPTED=false   
    volumes:
      - ./mounts/neo4j/data:/var/lib/neo4j/data # Data Mount
      - ./mounts/neo4j/import:/var/lib/neo4j/import

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "15672:15672"   # web management interface
      - "5672:5672"     # amqp
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  ####################################
  # End Fixtures
  ####################################

  ####################################
  # Begin Bots
  ####################################

  message-server:
    image: menome/message-server:latest
    ports:
      - "8081:8081"
    links:
      - neo4j
      - rabbitmq
    environment:
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_QUEUE=messageserver
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_HOST=bolt://neo4j
      - HTTP_SERVER_PORT=8081
      - RABBITMQ_BATCH_SIZE=5000
      - SHOW_CONNECTION_LOG_OUTPUT=Y
      - RABBITMQ_EXCHANGE=messageserver_exchange


  csvharvester:
    image: menome/csv_harvester:latest
    links:
      - rabbitmq
    environment:
      - NODE_ENV=development
      - RABBIT_OUTGOING_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672?heartbeat=3600
      - RABBIT_OUTGOING_ROUTING_KEY=messageserver
      - RABBIT_OUTGOING_EXCHANGE=messageserver_exchange
      - RABBIT_OUTGOING_EXCHANGE_TYPE=direct

    ports: 
      - 3021:80
    volumes:
      - ./models:/srv/app/models
      - ./local:/srv/app/local

  ####################################
  # End Bots
  ####################################

  ####################################
  # Begin Customer Facing
  ####################################

